### ISSUE TITLE
CLOSE button is disable when error in Request Invitation dialog box

### ISSUE THREAD

**Issue by jasnow** [RailsApps/rails-prelaunch-signup#14]
Want to verify that other people see this condition too.

Using **RailsApp's Startup Prelaunch Signup App**

Entered "Request Invitation" email already used, get error and disabled
CLOSE button and disable X in top right corner. Is that correct?

i have to close the tab in the browser to get rid of the dialog box.

**Comment by DanielKehoe** [comment]
Thanks for reporting. I'll investigate.

**Comment by DanielKehoe** [comment]
Yep, there's an issue. I've verified it but haven't found a fix yet.

**Comment by jasnow** [comment]
Thanks for the updates. I have fixed the two rspec tests and a couple "brakeman" security issues. I will write them up soon.

**Comment by jasnow** [comment]
closed it by mistake

**Comment by DanielKehoe** [comment]
I've fixed this issue with commit 00eabe6378f87823c5cd6d4613b90cb9965e6d4b.

The file _app/views/devise/registrations/new.html.erb_ needs:

```
<div id="request-invite" class="modal" style="display: <%= @user.errors.any? ? 'block' : 'none';%>">
```

Please test and reopen the issue if the problem is not resolved.

**Comment by jaqbyte** [comment]
Hi, just started with rails. The bug still exists.

**Comment by Jacubeit** [comment]
Hi, update: The bug does not exist if you just download the repo here. If you follow the tutorial, it still exists.

**Comment by exawatt** [comment]
I have the same problem. I think it is caused by the fact that the Rails `@user.errors` object still contains errors, even when you try to dismiss the modal. Thus the code `<%= @user.errors.any? ? 'block' : 'none';%>` always evaluates to true and places the modal div in `block` style, even when you meant to dismiss it.

You have to clear the `@user.errors` object when the user clicks X or CLOSE button, so that the `@user.errors` object won't evaluate to true anymore and the display style of the div can be "none".  I worked around this by explicitly setting the href of the target as follows:

```
<a class="close" data-dismiss="modal" href="/">
```

I guess you could target a function to actually clear the object. But I feel like there should be a more satisfying solution?
